#!/bin/bash
if [ ! -d "demos/facemesh/code/venv" ]; then
  python3 -m venv demos/facemesh/code/venv
fi
source demos/facemesh/code/venv/bin/activate
python3 -m pip install -r requirements.txt
python3 demo.py -e -xyz -3 world 
printf "demo started"